### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by BangDori** [asuan99/dgb-challengers#4]
# indexPage

- 로그인
  - [ ] 아이디 & 패스워드 불일치 -> 에러메시지
- 회원가입
  - [ ] 아이디 중복일 경우 -> 에러메시지
  - [ ] 회원가입 성공시 -> 회원가입 성공 메시지

# userPage

- 은퇴계산기
  - 은퇴계산식 및 차트 자료 필요
- 포트폴리오
  - 내 포트폴리오
    - 보유 종목, 보유 금액
    - 목표금액 달성률, 남은 기한, 은퇴 달성률 ( 화면 구상 다시 해야할듯 )
    - 증시 요약 정보, 경제 뉴스 핫토픽 ( 일단 뉴스정보 복사 붙여넣기 )
  - 포트폴리오 비교 & Rank
